# Generated by Django 5.1.6 on 2025-02-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('EC', 'Electronics and Communication'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='CS', max_length=100)),
                ('register_num', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
